### ISSUE TITLE
リアクション用のツールパッドを作る

### ISSUE THREAD

**Issue by elecdeer** [jphacks/C_2101#124]
<img width="211" alt="スクリーンショット 2021-11-06 13 32 10" src="https://user-images.githubusercontent.com/37701077/140597905-3787179f-8ea6-431a-a6ab-1fa8f78d60d1.png">
こういうやつ？
候補絞るか、全部のEmojiを表示するかは悩みどころ

**Comment by averak** [comment]
候補絞った方が良さそう

**Comment by takex5g** [comment]
参考用メモ
https://live.catnose99.com/
<img width="345" alt="スクリーンショット 2021-11-11 22 55 12" src="https://user-images.githubusercontent.com/7685537/141310294-4a24fbf9-232b-4c6b-901e-6b1b6b1f78c7.png">
